DROP TABLE IF EXISTS users;

CREATE TABLE users (
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    token VARCHAR(64),
    CHECK (role IN ('CONTESTANT', 'COMMITTEE', 'SUPPORT')) 
)
