export const CLARIFICATION_VERSION_MAJOR = 1;
export const CLARIFICATION_VERSION_MINOR = 0;
export const CLARIFICATION_VERSION_PATCH = 0;
export const CLARIFICATION_VERSION = `${CLARIFICATION_VERSION_MAJOR}.${CLARIFICATION_VERSION_MINOR}.${CLARIFICATION_VERSION_PATCH}`;